name: Advanced Monitoring with Telegram

on:
  workflow_run:
    workflows: ["CI", "Build", "Deploy"]
    types: [completed, requested]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed, merged]
  release:
    types: [published]

jobs:
  monitor-workflow:
    if: github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Success Notification
        if: github.event.workflow_run.conclusion == 'success'
        uses: asychin/telegram-notify-action@v3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: success
          message: |
            ✅ **Workflow успешно завершен**
            
            🔄 **Workflow:** {{workflow}}
            📋 **Задача:** {{job}}
            🏃 **Runner:** {{runnerName}} на {{runnerOs}}
            🏗️ **Архитектура:** {{runnerArch}}
            
            📊 **Статистика запуска:**
            - ID запуска: {{runId}}
            - Номер: {{runNumber}}
            - Попытка: {{runAttempt}}
            - Событие: {{eventName}}
            
            🏢 **Репозиторий:**
            - Владелец: {{repositoryOwner}}
            - ID: {{repositoryId}}
            - Защищенная ветка: {{refProtected}}
            
            🌐 **Окружение:**
            - GitHub Actions: {{actionsEnvironment}}
            - ID окружения: {{actionsEnvironmentId}}
            - Workspace: {{workspace}}
            - Temp: {{runnerTemp}}

      - name: Workflow Failure Notification
        if: github.event.workflow_run.conclusion == 'failure'
        uses: asychin/telegram-notify-action@v3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: error
          message: |
            ❌ **Workflow завершился с ошибкой**
            
            🔄 **Workflow:** {{workflow}}
            📋 **Задача:** {{job}}
            🚫 **Статус:** {{jobStatus}}
            
            🔍 **Детали ошибки:**
            - Запуск: #{{runNumber}} (ID: {{runId}})
            - Попытка: {{runAttempt}}
            - SHA: {{sha}}
            - Ветка: {{refName}}
            
            👤 **Инициатор:** {{actor}}
            🏢 **Репозиторий:** {{repository}}
            🔗 **Ссылка:** {{serverUrl}}/{{repository}}/actions/runs/{{runId}}

  monitor-issues:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: New Issue Notification
        if: github.event.action == 'opened'
        uses: asychin/telegram-notify-action@v3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: warning
          message: |
            🐛 **Новый Issue**
            
            **Автор:** {{issueAuthor}}
            **Заголовок:** {{issueTitle}}
            **Номер:** #{{issueNumber}}
            **Состояние:** {{issueState}}
            **Метки:** {{labels}}
            
            🏢 **Репозиторий:** {{repository}}
            👤 **Владелец:** {{repositoryOwner}}
            🔗 **Ссылка:** {{issueUrl}}
            
            📝 **Описание:**
            {{issueBody}}

      - name: Issue Closed Notification
        if: github.event.action == 'closed'
        uses: asychin/telegram-notify-action@v3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: success
          message: |
            ✅ **Issue закрыт**
            
            **Заголовок:** {{issueTitle}}
            **Номер:** #{{issueNumber}}
            **Закрыл:** {{actor}}
            
            🏢 **Репозиторий:** {{repository}}
            🔗 **Ссылка:** {{issueUrl}}

  monitor-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Notification
        uses: asychin/telegram-notify-action@v3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: info
          message: |
            🔄 **Pull Request {{prAction}}**
            
            **Заголовок:** {{prTitle}}
            **Номер:** #{{prNumber}}
            **Автор:** {{prAuthor}}
            **Состояние:** {{prState}}
            
            🔀 **Ветки:**
            - Из: {{prHeadRef}} ({{prHeadSha}})
            - В: {{prBaseRef}}
            
            🏢 **Репозиторий:** {{repository}}
            👤 **Владелец:** {{repositoryOwner}}
            🔗 **Ссылка:** {{prUrl}}
            
            📊 **Статистика:**
            - Коммиты: {{prCommits}}
            - Изменения: +{{prAdditions}} -{{prDeletions}}
            - Файлов: {{prChangedFiles}}

  scheduled-health-check:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Health Check Report
        uses: asychin/telegram-notify-action@v3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: info
          message: |
            🏥 **Периодическая проверка здоровья**
            
            🕒 **Время проверки:** {{triggeredAt}}
            🏢 **Репозиторий:** {{repository}}
            👤 **Владелец:** {{repositoryOwner}}
            
            🌐 **Окружение GitHub Actions:**
            - Среда: {{actionsEnvironment}}
            - ID среды: {{actionsEnvironmentId}}
            - URL: {{actionsEnvironmentUrl}}
            
            🏃 **Runner информация:**
            - Имя: {{runnerName}}
            - ОС: {{runnerOs}}
            - Архитектура: {{runnerArch}}
            - Рабочая папка: {{workspace}}
            - Временная папка: {{runnerTemp}}
            
            🔗 **Ссылки:**
            - Сервер: {{serverUrl}}
            - API: {{apiUrl}}
            - GraphQL: {{graphqlUrl}}
            
            ✅ Все системы работают нормально!
