name: Basic Telegram Notification

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send basic notification
        uses: asychin/telegram-notify-action@v3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: info
          message: |
            🚀 **Новое событие в репозитории**
            
            **Репозиторий:** {{repository}}
            **Ветка:** {{refName}}
            **Событие:** {{eventName}}
            **Автор:** {{actor}}
            **SHA:** {{sha}}
            **Workflow:** {{workflow}}
            **Задача:** {{job}}
            **Запуск:** #{{runNumber}}
            
            🏢 **Владелец:** {{repositoryOwner}}
            🔗 **URL:** {{serverUrl}}/{{repository}}

      - name: Send notification with custom variables
        uses: asychin/telegram-notify-action@v3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: success
          message: |
            ✅ **Успешное выполнение**
            
            **Окружение:** {{actionsEnvironment}}
            **Runner:** {{runnerName}} ({{runnerOs}})
            **Архитектура:** {{runnerArch}}
            **Workspace:** {{workspace}}
            
            📊 **Детали запуска:**
            - ID: {{runId}}
            - Номер: {{runNumber}}
            - Попытка: {{runAttempt}}
            - Тип ссылки: {{refType}}

