name: Deployment with Updates

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    steps:
      - name: Pre-deployment notification
        uses: asychin/telegram-notify-action@v3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: info
          message: |
            🚀 **Начало деплоя**
            
            🎯 **Окружение:** {{actionsEnvironment}}
            📝 **ID окружения:** {{actionsEnvironmentId}}
            🔗 **URL окружения:** {{actionsEnvironmentUrl}}
            
            📦 **Версия:** {{tagName}}
            🏷️ **Имя релиза:** {{releaseName}}
            👤 **Автор релиза:** {{releaseAuthor}}
            
            🏢 **Репозиторий:** {{repository}}
            👤 **Владелец:** {{repositoryOwner}}
            🔗 **Ссылка на релиз:** {{releaseUrl}}
            
            🏃 **Runner:** {{runnerName}} на {{runnerOs}}
            🏗️ **Архитектура:** {{runnerArch}}
            📁 **Workspace:** {{workspace}}

      - name: Deploy to environment
        id: deploy
        run: |
          echo "Deploying to ${{ github.event.inputs.environment || 'production' }}..."
          
          # Simulate deployment
          sleep 10
          
          # Simulate success/failure (for demo)
          if [ "${{ github.event.inputs.environment }}" = "production" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "deploy_url=https://example.com" >> $GITHUB_OUTPUT
          else
            echo "status=success" >> $GITHUB_OUTPUT
            echo "deploy_url=https://staging.example.com" >> $GITHUB_OUTPUT
          fi

      - name: Successful deployment notification
        if: steps.deploy.outputs.status == 'success'
        uses: asychin/telegram-notify-action@v3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: success
          message: |
            ✅ **Деплой успешно завершен**
            
            🎯 **Окружение:** {{actionsEnvironment}}
            🌐 **URL:** ${{ steps.deploy.outputs.deploy_url }}
            
            📊 **Информация о запуске:**
            - ID: {{runId}}
            - Номер: {{runNumber}}
            - Попытка: {{runAttempt}}
            - Workflow: {{workflow}}
            - Задача: {{job}}
            
            🏢 **Репозиторий:** {{repository}}
            👤 **Деплоил:** {{actor}}
            🕒 **Время запуска:** {{triggeredAt}}
            
            🖥️ **Система:**
            - Runner: {{runnerName}}
            - ОС: {{runnerOs}}
            - Архитектура: {{runnerArch}}
            - Tool Cache: {{runnerToolCache}}
            - Temp: {{runnerTemp}}
            
            🌐 **GitHub Environment:**
            - API: {{apiUrl}}
            - GraphQL: {{graphqlUrl}}
            - Server: {{serverUrl}}
          
      - name: Failed deployment notification
        if: failure()
        uses: asychin/telegram-notify-action@v3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: error
          message: |
            ❌ **Деплой завершился с ошибкой**
            
            🎯 **Окружение:** {{actionsEnvironment}}
            🚫 **Статус задачи:** {{jobStatus}}
            
            📊 **Информация о запуске:**
            - ID: {{runId}}
            - Номер: {{runNumber}}
            - Попытка: {{runAttempt}}
            - Workflow: {{workflow}}
            - Задача: {{job}}
            
            🏢 **Репозиторий:** {{repository}}
            👤 **Инициатор:** {{actor}}
            🔗 **Ссылка на запуск:** {{serverUrl}}/{{repository}}/actions/runs/{{runId}}
            
            🖥️ **Система:**
            - Runner: {{runnerName}}
            - ОС: {{runnerOs}}
            - Рабочая папка: {{workspace}}

  post-deployment:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Post-deployment summary
        uses: asychin/telegram-notify-action@v3
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: info
          message: |
            📋 **Отчет о деплое**
            
            🎯 **Окружение:** {{actionsEnvironment}}
            📊 **Результат:** ${{ needs.deploy.result }}
            
            🔍 **Детали GitHub:**
            - Репозиторий: {{repository}}
            - ID репозитория: {{repositoryId}}
            - Владелец: {{repositoryOwner}}
            - ID владельца: {{repositoryOwnerId}}
            
            🔗 **Защита ветки:** {{refProtected}}
            📝 **Тип ссылки:** {{refType}}
            🌿 **Ветка:** {{refName}}
            🆔 **SHA:** {{sha}}
            
            🏃 **Система выполнения:**
            - Имя: {{runnerName}}
            - ОС: {{runnerOs}}
            - Архитектура: {{runnerArch}}
            - Tool Cache: {{runnerToolCache}}
            - Temp Directory: {{runnerTemp}}
            - Workspace: {{workspace}}
            
            🌐 **GitHub Окружение:**
            - ID: {{actionsEnvironmentId}}
            - URL: {{actionsEnvironmentUrl}}
          template_vars: |
            {
              "deploymentResult": "${{ needs.deploy.result }}",
              "finalStatus": "${{ needs.deploy.result == 'success' && '✅ Успешно' || '❌ Неудачно' }}"
            }
