# 🎯 Comprehensive Usage Examples for Telegram Notify Action
#
# This file demonstrates various use cases and configurations
# for the telegram-notify-action with AUTO-CONTEXT VARIABLES

name: Telegram Notify Usage Examples

on:
  workflow_dispatch:
    inputs:
      example_type:
        description: "Choose example to run"
        required: true
        default: "basic"
        type: choice
        options:
          - basic
          - templates
          - files
          - keyboards
          - conditions

jobs:
  # 📝 BASIC MESSAGING EXAMPLES
  basic-examples:
    name: Basic Examples
    runs-on: ubuntu-latest
    if: github.event.inputs.example_type == 'basic'
    steps:
      - uses: actions/checkout@v4

      - name: Simple text message
        uses: ./
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            📢 **Простое сообщение**
            
            Автоматические переменные:
            - Репозиторий: {{repository}}
            - Владелец: {{repositoryOwner}}
            - Workflow: {{workflow}}
            - Runner: {{runnerName}} на {{runnerOs}}

      - name: HTML formatted message
        uses: ./
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          parse_mode: "HTML"
          message: |
            <b>🎨 HTML форматирование</b>
            
            <b>Репозиторий:</b> <code>{{repository}}</code>
            <b>Актор:</b> <i>{{actor}}</i>
            <b>SHA:</b> <code>{{sha}}</code>
            <b>Runner:</b> {{runnerName}} ({{runnerOs}})

      - name: Markdown formatted message
        uses: ./
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          parse_mode: "Markdown"
          message: |
            **📋 Markdown форматирование**
            
            **Workflow:** `{{workflow}}`
            **Запуск:** #{{runNumber}}
            **Ветка:** `{{refName}}`
            **Время:** {{triggeredAt}}

  # 🎨 TEMPLATE EXAMPLES
  template-examples:
    name: Template Examples
    runs-on: ubuntu-latest
    if: github.event.inputs.example_type == 'templates'
    strategy:
      matrix:
        template: [success, error, warning, info, deploy, test, release]
    steps:
      - uses: actions/checkout@v4

      - name: ${{ matrix.template }} template example
        uses: ./
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: ${{ matrix.template }}
          message: |
            🎨 **Шаблон: ${{ matrix.template }}**
            
            Автоматические переменные в действии:
            - Репозиторий: {{repository}}
            - Владелец: {{repositoryOwner}}
            - ID репозитория: {{repositoryId}}
            - Workflow: {{workflow}}
            - Задача: {{job}}
            - Запуск: #{{runNumber}} (ID: {{runId}})
            - Runner: {{runnerName}} на {{runnerOs}}
            - Архитектура: {{runnerArch}}
            - Актор: {{actor}}
            - Событие: {{eventName}}
            - Время: {{triggeredAt}}

  # 📎 FILE UPLOAD EXAMPLES
  file-examples:
    name: File Upload Examples
    runs-on: ubuntu-latest
    if: github.event.inputs.example_type == 'files'
    steps:
      - uses: actions/checkout@v4

      - name: Create sample files
        run: |
          echo "Sample document content" > sample.txt
          echo "Repository: {{repository}}" >> sample.txt
          echo "Workflow: {{workflow}}" >> sample.txt
          echo "Runner: {{runnerName}}" >> sample.txt
          
          # Create a simple JSON file
          cat > data.json << EOF
          {
            "repository": "{{repository}}",
            "workflow": "{{workflow}}",
            "runNumber": "{{runNumber}}",
            "actor": "{{actor}}"
          }
          EOF

      - name: Send document
        uses: ./
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          file_path: "sample.txt"
          file_type: "document"
          caption: |
            📄 **Документ загружен**
            
            Контекст:
            - Репозиторий: {{repository}}
            - Workflow: {{workflow}}
            - Runner: {{runnerName}} на {{runnerOs}}
            - Время: {{triggeredAt}}

      - name: Send JSON data
        uses: ./
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          file_path: "data.json"
          file_type: "document"
          caption: |
            📊 **JSON данные**
            
            Автоматические переменные GitHub:
            - ID репозитория: {{repositoryId}}
            - Владелец: {{repositoryOwner}}
            - SHA: {{sha}}
            - Ветка: {{refName}} ({{refType}})

  # ⌨️ KEYBOARD EXAMPLES
  keyboard-examples:
    name: Inline Keyboard Examples
    runs-on: ubuntu-latest
    if: github.event.inputs.example_type == 'keyboards'
    steps:
      - uses: actions/checkout@v4

      - name: Simple inline keyboard
        uses: ./
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            ⌨️ **Простая клавиатура**
            
            Репозиторий: {{repository}}
            Workflow: {{workflow}}
            Runner: {{runnerName}}
          inline_keyboard: |
            [
              {"text": "🏠 Репозиторий", "url": "{{serverUrl}}/{{repository}}"},
              {"text": "🔄 Workflow", "url": "{{serverUrl}}/{{repository}}/actions/runs/{{runId}}"}
            ]

      - name: Multi-row keyboard
        uses: ./
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: "info"
          message: |
            🎛️ **Многорядная клавиатура**
            
            GitHub контекст:
            - Сервер: {{serverUrl}}
            - API: {{apiUrl}}
            - GraphQL: {{graphqlUrl}}
          inline_keyboard: |
            [
              [
                {"text": "📊 Actions", "url": "{{serverUrl}}/{{repository}}/actions"},
                {"text": "📈 Insights", "url": "{{serverUrl}}/{{repository}}/pulse"}
              ],
              [
                {"text": "🔒 Security", "url": "{{serverUrl}}/{{repository}}/security"},
                {"text": "⚙️ Settings", "url": "{{serverUrl}}/{{repository}}/settings"}
              ],
              [
                {"text": "📝 Issues", "url": "{{serverUrl}}/{{repository}}/issues"},
                {"text": "🔀 Pull Requests", "url": "{{serverUrl}}/{{repository}}/pulls"}
              ]
            ]

  # 🔀 CONDITIONAL EXAMPLES
  conditional-examples:
    name: Conditional Sending Examples
    runs-on: ubuntu-latest
    if: github.event.inputs.example_type == 'conditions'
    steps:
      - uses: actions/checkout@v4

      - name: Success only notification
        uses: ./
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          send_on_success: true
          send_on_failure: false
          template: "success"
          message: |
            ✅ **Только при успехе**
            
            Это сообщение отправляется только при успешном выполнении.
            
            Контекст:
            - Репозиторий: {{repository}}
            - Статус задачи: {{jobStatus}}
            - Runner: {{runnerName}}

      - name: Always send notification
        uses: ./
        if: always()
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: "info"
          message: |
            📢 **Всегда отправляется**
            
            Это сообщение отправляется независимо от результата.
            
            GitHub Actions контекст:
            - Workflow: {{workflow}}
            - Задача: {{job}}
            - Запуск: #{{runNumber}}
            - Актор: {{actor}}
            - Окружение: {{actionsEnvironment}}
            - Workspace: {{workspace}}
            - Tool Cache: {{runnerToolCache}}

  # 📊 COMPREHENSIVE EXAMPLE
  comprehensive-example:
    name: Comprehensive Example
    runs-on: ubuntu-latest
    if: always()
    needs: [basic-examples, template-examples, file-examples, keyboard-examples, conditional-examples]
    steps:
      - uses: actions/checkout@v4

      - name: Final comprehensive notification
        uses: ./
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          template: "release"
          language: "ru"
          message: |
            🎉 **Комплексный пример завершен**
            
            📊 **Полный контекст GitHub Actions:**
            
            🏢 **Репозиторий:**
            - Название: {{repository}}
            - Владелец: {{repositoryOwner}}
            - ID: {{repositoryId}}
            - ID владельца: {{repositoryOwnerId}}
            
            🌿 **Git контекст:**
            - Ссылка: {{ref}}
            - Имя ветки: {{refName}}
            - Тип: {{refType}}
            - Защищена: {{refProtected}}
            - SHA: {{sha}}
            
            🔄 **Workflow контекст:**
            - Название: {{workflow}}
            - Ссылка: {{workflowRef}}
            - SHA: {{workflowSha}}
            - Задача: {{job}}
            - Статус: {{jobStatus}}
            
            🏃 **Запуск:**
            - ID: {{runId}}
            - Номер: {{runNumber}}
            - Попытка: {{runAttempt}}
            - Событие: {{eventName}}
            - Актор: {{actor}}
            - ID актора: {{actorId}}
            - Время: {{triggeredAt}}
            
            🖥️ **Runner:**
            - Имя: {{runnerName}}
            - ОС: {{runnerOs}}
            - Архитектура: {{runnerArch}}
            - Workspace: {{workspace}}
            - Tool Cache: {{runnerToolCache}}
            - Temp: {{runnerTemp}}
            
            🌐 **Окружение:**
            - GitHub Actions: {{actionsEnvironment}}
            - ID окружения: {{actionsEnvironmentId}}
            - URL окружения: {{actionsEnvironmentUrl}}
            
            🔗 **URLs:**
            - Сервер: {{serverUrl}}
            - API: {{apiUrl}}
            - GraphQL: {{graphqlUrl}}
          inline_keyboard: |
            [
              [
                {"text": "🏠 Репозиторий", "url": "{{serverUrl}}/{{repository}}"},
                {"text": "🔄 Этот запуск", "url": "{{serverUrl}}/{{repository}}/actions/runs/{{runId}}"}
              ],
              [
                {"text": "📊 Все Actions", "url": "{{serverUrl}}/{{repository}}/actions"},
                {"text": "📈 Аналитика", "url": "{{serverUrl}}/{{repository}}/pulse"}
              ],
              [
                {"text": "🔒 Безопасность", "url": "{{serverUrl}}/{{repository}}/security"},
                {"text": "⚙️ Настройки", "url": "{{serverUrl}}/{{repository}}/settings"}
              ]
            ]