name: File Upload Test
on:
  workflow_dispatch:
jobs:
  file-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Create test file
        run: echo "Test content" > test-upload.txt
      - name: Test file upload
        uses: ./
        continue-on-error: true
        with:
          telegram_token: "dummy_token"
          chat_id: "123456789"
          file_path: "test-upload.txt"
          file_type: "document"
          caption: "Test upload"
          max_retries: 2
